[tool.poetry]
name = "aoc"
version = "0.1.0"
description = "Solutions to advent of code 2021."
authors = ["Jake Scott"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
